name: mpflutter_gamemo
description: The gallery of MPFlutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  mpflutter_core: ^2.7.5
  mpflutter_build_tools: ^2.7.7
  mpflutter_wegame_api:
    git:
      url: https://github.com/mpflutter/mpflutter_wegame_api.git
  mpflutter_wechat_api: ^2.2.4
  es_compression: 2.0.12
  get: ^4.6.6
  flutter_screenutil: 5.9.3
  pull_to_refresh: ^2.0.0
  pretty_dio_logger: ^1.4.0
  dio: ^5.6.0
  flutter_spinkit: 5.1.0
  flutter_easyloading: 3.0.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  mpflutter_wechat_editable: ^0.0.2
  flutter_widget_from_html: ^0.15.2
  # 接入IM专用依赖 START
  web_socket_channel: # MpFlutter专用
    git:
      url: https://github.com/mpflutter/web_socket_channel.git
      ref: mpflutter-2.4.2
  flutter_openim_sdk: # dart专用，纯websocket模式，不需要接其他sdk
    git:
      url: https://e.coding.net/thesetech/mpflutter/open-im-sdk-flutter.git
      ref: for-dart-js-server
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  extended_keyboard: ^0.0.3
#  qr_code_scanner: ^1.0.1
  # 接入IM专用依赖
dependency_overrides:
  audioplayers_web:
    git:
      url: https://github.com/mpflutter/audioplayers.git
      ref: mpflutter-v5.2.1
      path: packages/audioplayers_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Noto Sans SC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
  shaders:
    - shaders/simple.frag
  assets:
    # - assets/
    - assets/images/
    - assets/music/
    - assets/sfx/
